# Generated by Django 3.1.4 on 2020-12-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20201226_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_likes',
        ),
    ]
